dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: data/ptb/
    train_path: ptb_train.conllx
    dev_path: ptb_dev.conllx
    test_path: ptb_test.conllx
  embeddings:
    type: token
    root: data/ptb/
    train_path: ptb_train.hdf5
    dev_path: ptb_dev.hdf5
    test_path: ptb_test.hdf5
    break_on_qmark: False
  batch_size: 40
model:
  hidden_dim: 1024
  model_type: BERT-disk
  use_disk: True
  model_layer: -1  # Doesn't matter, gets overwritten by script that iterates over layers.
probe:
  task_signature: word_pair # word, word_pair
  task_name: parse-distance  # parse-depth, parse-distance
  num_layers: 1
  maximum_rank: 32
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: saved_models/example/model_dist_1layer/model_dist
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
    - uuas
